export 'package:orgg_widget_app/presentacion/screens/animated/animated_screen.dart';
export 'package:orgg_widget_app/presentacion/screens/app_tutorial/app_tutorial_screen.dart';
export 'package:orgg_widget_app/presentacion/screens/buttons/button_screen.dart';
export 'package:orgg_widget_app/presentacion/screens/card/cards_screen.dart';
export 'package:orgg_widget_app/presentacion/screens/home/home_screens.dart';
export 'package:orgg_widget_app/presentacion/screens/infinite_scroll/infinite_scroll_screen.dart';
export 'package:orgg_widget_app/presentacion/screens/progress/progress_screen.dart';
export 'package:orgg_widget_app/presentacion/screens/snackbar/snackbar_screen.dart';
export 'package:orgg_widget_app/presentacion/screens/ui_controls/ui_controls_screen.dart';